### ISSUE TITLE
Adding comments to lessons

### ISSUE THREAD

**Issue by JithinKS97** [JithinKS97/dynamic-learning#36]
@ashneeldas2 has started implementing this feature. But at present, we have a single comments thread for the whole of lesson. Should we change it as having a comments thread for each of the slide?

**Comment by ashneeldas2** [comment]
I agree, that is a good idea. I will implement this tomorrow morning by passing the slide as a prop to the comment component.

**Comment by JithinKS97** [comment]
This is a suggestion. For the discussion forum,  many React components are created for adding and editing comments etc. Can we reuse those components instead of creating components from scratch. May be I can guide you through those codes if you want.

**Comment by ashneeldas2** [comment]
We can use those components to do it; however, the currently existing comment system is for requests and lessonplans which is why I created an entirely new component to correspond to lessons only. However, if you think there is a way to use the existing components for this then I would be willing to switch to using those if you could explain how they work.
